### ISSUE TITLE
kali -other error

### ISSUE THREAD

**Issue by lianfeng30** [OrOneEqualsOne/Recon#3]
Process AskEnum-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "bin/Sublist3r/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "bin/Sublist3r/sublist3r.py", line 237, in enumerate
    links = self.extract_domains(resp)
  File "bin/Sublist3r/sublist3r.py", line 395, in extract_domains
    return links_list
UnboundLocalError: local variable 'links_list' referenced before assignment

**Comment by OrOneEqualsOne** [comment]
lianfeng30, Thank you for reporting these issues and your patience. I have written in additional error checking and conducted additional testing  - can you please check if you receive the same issue with the updated script?

**Comment by lianfeng30** [comment]
thanks
